/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.culminating_robertchen;

import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.util.ArrayList;
import javax.swing.ButtonGroup;

/**
 *
 * @author 335091559
 */
import javax.swing.ImageIcon;
public class Display extends javax.swing.JFrame {

    /**
     * Creates new form Display
     */
    ImageIcon deletePNG = new ImageIcon("delete.png");
    String eventName, beginTime, finishTime, subtaskOne, subtaskTwo, subtaskThree, n, st, 
            et, sb1, sb2, sb3;
    boolean daily = false;
    int count1 = 0, count2 = 0, count3 = 0, id = 0;
    ArrayList<Task> tasks = new ArrayList<>();
    ArrayList<Task> addedTask = new ArrayList<>();
    ButtonGroup group = new ButtonGroup();
    
    public Display() {
        initComponents();
        String underline = "<html><u>Task Name</u></html>";
        activityName.setText(underline);
        group.add(yesCreate);
        group.add(noCreate);
        
        getContentPane().setBackground(Color.orange);
        delete.setIcon(deletePNG);
    }
    
    // Checks if the text areas in the create popup are empty
    public boolean checkEmpty() {
        if (createPopUp.isVisible() == true)  {
            if (createTaskName.getText().isEmpty() || createStartTime.getText().isEmpty()
                    || createEndTime.getText().isEmpty()) {
                return true;
            } else {
                return false;
            }
        } else {
            if (editTaskName.getText().isEmpty() || editStartTime.getText().isEmpty()
                    || editEndTime.getText().isEmpty()) {
                return true;
            } else {
                return false;
            }
        }
    }
    
    // Clears everything on the create popup
    public void clear() {
        createTaskName.setText("");
        createStartTime.setText("");
        createEndTime.setText("");
        createSubtask1.setText("");
        createSubtask2.setText("");
        createSubtask3.setText("");
        group.clearSelection();
    }
    
    // Sets the task on the home page to have the information inputted in the create popup
    public void addTask(String n, String st, String et, String sb1, String sb2, String sb3) {
        n = addedTask.get(0).getName();
        activityName.setText(n);
        st = addedTask.get(0).getStartTime();
        startTaskTime.setText(st);
        et = addedTask.get(0).getEndTime();
        endTaskTime.setText(et);
        sb1 = addedTask.get(0).getSubtask1();
        subActivity1.setText(sb1);
        sb2 = addedTask.get(0).getSubtask2();
        subActivity2.setText(sb2);
        sb3 = addedTask.get(0).getSubtask3();
        subActivity3.setText(sb3);
    }
    
    // Gets the information of a task
    public void getTask(String n, String st, String et, String sb1, String sb2, String sb3) {
        n = addedTask.get(0).getName();
        editTaskName.setText(n);
        st = addedTask.get(0).getStartTime();
        editStartTime.setText(st);
        et = addedTask.get(0).getEndTime();
        editEndTime.setText(et);
        sb1 = addedTask.get(0).getSubtask1();
        editSubtask1.setText(sb1);
        sb2 = addedTask.get(0).getSubtask2();
        editSubtask2.setText(sb2);
        sb3 = addedTask.get(0).getSubtask3();
        editSubtask3.setText(sb3);
    }
    
    // Gets the information
    public void getInfo(int selectedId) {
        n = addedTask.get(selectedId).getName();
        st = addedTask.get(selectedId).getStartTime();
        et = addedTask.get(selectedId).getEndTime();
        sb1 = addedTask.get(selectedId).getSubtask1();
        sb2 = addedTask.get(selectedId).getSubtask2();
        sb3 = addedTask.get(selectedId).getSubtask3();
    }
    
    // Fills in the text areas for the edit popup
    public void editTask(int selectedId, String na, String stt, String ent, String sub1, 
            String sub2, String sub3) {
        tasks.get(selectedId).setName(na);
        tasks.get(selectedId).setStartTime(stt);
        tasks.get(selectedId).setEndTime(ent);
        tasks.get(selectedId).setSubtask1(sub1);
        tasks.get(selectedId).setSubtask2(sub2);
        tasks.get(selectedId).setSubtask3(sub3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createPopUp = new javax.swing.JFrame();
        createTitle = new javax.swing.JLabel();
        createStartTimePrompt = new javax.swing.JLabel();
        createStartTime = new com.github.lgooddatepicker.components.TimePicker();
        createEndTimePrompt = new javax.swing.JLabel();
        createEndTime = new com.github.lgooddatepicker.components.TimePicker();
        createTaskNamePrompt = new javax.swing.JLabel();
        createSubtask1Prompt = new javax.swing.JLabel();
        createSubtask2Prompt = new javax.swing.JLabel();
        createSubtask3Prompt = new javax.swing.JLabel();
        createTaskName = new javax.swing.JTextField();
        createSubtask1 = new javax.swing.JTextField();
        createSubtask2 = new javax.swing.JTextField();
        createSubtask3 = new javax.swing.JTextField();
        createRepeatingTaskPrompt = new javax.swing.JLabel();
        yesCreate = new javax.swing.JToggleButton();
        noCreate = new javax.swing.JToggleButton();
        createTask = new javax.swing.JButton();
        createOutput = new javax.swing.JTextField();
        editPopUp = new javax.swing.JFrame();
        editTaskNamePrompt = new javax.swing.JLabel();
        editTask = new javax.swing.JButton();
        editSubtask1Prompt = new javax.swing.JLabel();
        editCreateOutput = new javax.swing.JTextField();
        editSubtask2Prompt = new javax.swing.JLabel();
        editSubtask3Prompt = new javax.swing.JLabel();
        editTaskName = new javax.swing.JTextField();
        editSubtask1 = new javax.swing.JTextField();
        editCreateTitle = new javax.swing.JLabel();
        editSubtask2 = new javax.swing.JTextField();
        editStartTimePrompt = new javax.swing.JLabel();
        editSubtask3 = new javax.swing.JTextField();
        editStartTime = new com.github.lgooddatepicker.components.TimePicker();
        editRepeatingTaskPrompt = new javax.swing.JLabel();
        editEndTimePrompt = new javax.swing.JLabel();
        yesEdit = new javax.swing.JToggleButton();
        editEndTime = new com.github.lgooddatepicker.components.TimePicker();
        noEdit = new javax.swing.JToggleButton();
        buttonGroup = new javax.swing.ButtonGroup();
        day = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        subActivity1 = new javax.swing.JRadioButton();
        subActivity2 = new javax.swing.JRadioButton();
        subActivity3 = new javax.swing.JRadioButton();
        activityName = new javax.swing.JLabel();
        startTaskTime = new javax.swing.JLabel();
        startTimeLabel = new javax.swing.JLabel();
        endTimeLabel = new javax.swing.JLabel();
        endTaskTime = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        createTitle.setText("Create Task");
        createTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        createStartTimePrompt.setText("Start Time:");

        createEndTimePrompt.setText("End Time:");

        createTaskNamePrompt.setText("Task Name:");

        createSubtask1Prompt.setText("Subtask 1:");

        createSubtask2Prompt.setText("Subtask 2:");

        createSubtask3Prompt.setText("Subtask 3:");

        createRepeatingTaskPrompt.setText("Repeating Task:");

        yesCreate.setText("Yes");
        yesCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesCreateActionPerformed(evt);
            }
        });

        noCreate.setText("No");
        noCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noCreateActionPerformed(evt);
            }
        });

        createTask.setText("Create");
        createTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTaskActionPerformed(evt);
            }
        });

        createOutput.setEditable(false);

        javax.swing.GroupLayout createPopUpLayout = new javax.swing.GroupLayout(createPopUp.getContentPane());
        createPopUp.getContentPane().setLayout(createPopUpLayout);
        createPopUpLayout.setHorizontalGroup(
            createPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPopUpLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(createTask, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
            .addGroup(createPopUpLayout.createSequentialGroup()
                .addGroup(createPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createPopUpLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(createTitle))
                    .addGroup(createPopUpLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(createPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createPopUpLayout.createSequentialGroup()
                                .addComponent(createTaskNamePrompt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createPopUpLayout.createSequentialGroup()
                                .addComponent(createStartTimePrompt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(createEndTimePrompt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createPopUpLayout.createSequentialGroup()
                                    .addComponent(createSubtask3Prompt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(createSubtask3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createPopUpLayout.createSequentialGroup()
                                    .addComponent(createSubtask2Prompt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(createSubtask2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createPopUpLayout.createSequentialGroup()
                                    .addComponent(createSubtask1Prompt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(createSubtask1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(createOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(createPopUpLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(createRepeatingTaskPrompt)
                        .addGap(18, 18, 18)
                        .addComponent(yesCreate)
                        .addGap(30, 30, 30)
                        .addComponent(noCreate)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        createPopUpLayout.setVerticalGroup(
            createPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPopUpLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(createTitle)
                .addGap(36, 36, 36)
                .addGroup(createPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createTaskNamePrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(createPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createStartTimePrompt)
                    .addComponent(createStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createEndTimePrompt)
                    .addComponent(createEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(createPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createSubtask1Prompt)
                    .addComponent(createSubtask1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createSubtask2Prompt)
                    .addComponent(createSubtask2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createSubtask3Prompt)
                    .addComponent(createSubtask3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(createPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createRepeatingTaskPrompt)
                    .addComponent(yesCreate)
                    .addComponent(noCreate))
                .addGap(18, 18, 18)
                .addComponent(createTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        editTaskNamePrompt.setText("Task Name:");

        editTask.setText("Edit");
        editTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTaskActionPerformed(evt);
            }
        });

        editSubtask1Prompt.setText("Subtask 1:");

        editCreateOutput.setEditable(false);

        editSubtask2Prompt.setText("Subtask 2:");

        editSubtask3Prompt.setText("Subtask 3:");

        editCreateTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        editCreateTitle.setText("Edit Task");

        editStartTimePrompt.setText("Start Time:");

        editRepeatingTaskPrompt.setText("Repeating Task:");

        editEndTimePrompt.setText("End Time:");

        yesEdit.setText("Yes");
        yesEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesEditActionPerformed(evt);
            }
        });

        noEdit.setText("No");
        noEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPopUpLayout = new javax.swing.GroupLayout(editPopUp.getContentPane());
        editPopUp.getContentPane().setLayout(editPopUpLayout);
        editPopUpLayout.setHorizontalGroup(
            editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPopUpLayout.createSequentialGroup()
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPopUpLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editPopUpLayout.createSequentialGroup()
                                .addComponent(editTaskNamePrompt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editPopUpLayout.createSequentialGroup()
                                    .addComponent(editSubtask3Prompt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(editSubtask3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editPopUpLayout.createSequentialGroup()
                                    .addComponent(editSubtask2Prompt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(editSubtask2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editPopUpLayout.createSequentialGroup()
                                    .addComponent(editSubtask1Prompt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(editSubtask1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(editPopUpLayout.createSequentialGroup()
                                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(editCreateTitle)
                                    .addGroup(editPopUpLayout.createSequentialGroup()
                                        .addComponent(editStartTimePrompt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(editEndTimePrompt)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(editCreateOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editPopUpLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(editRepeatingTaskPrompt)
                        .addGap(18, 18, 18)
                        .addComponent(yesEdit)
                        .addGap(30, 30, 30)
                        .addComponent(noEdit)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPopUpLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(editTask, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        editPopUpLayout.setVerticalGroup(
            editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPopUpLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(editCreateTitle)
                .addGap(28, 28, 28)
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editTaskNamePrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editStartTimePrompt)
                    .addComponent(editStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editEndTimePrompt)
                    .addComponent(editEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSubtask1Prompt)
                    .addComponent(editSubtask1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSubtask2Prompt)
                    .addComponent(editSubtask2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSubtask3Prompt)
                    .addComponent(editSubtask3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editRepeatingTaskPrompt)
                    .addComponent(yesEdit)
                    .addComponent(noEdit))
                .addGap(18, 18, 18)
                .addComponent(editTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editCreateOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        day.setText("Date");
        day.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        day.setForeground(new java.awt.Color(153, 153, 255));

        create.setText("Create Activity");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(255, 178, 0));
        panel1.setForeground(new java.awt.Color(255, 153, 0));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        subActivity1.setText("Sub-task 1");
        subActivity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActivity1ActionPerformed(evt);
            }
        });

        subActivity2.setText("Sub-task 2");
        subActivity2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActivity2ActionPerformed(evt);
            }
        });

        subActivity3.setText("Sub-task 3");
        subActivity3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActivity3ActionPerformed(evt);
            }
        });

        activityName.setText("Task Name");
        activityName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        activityName.setForeground(new java.awt.Color(51, 102, 255));

        startTaskTime.setText("12:00am");

        startTimeLabel.setText("Start Time:");
        startTimeLabel.setForeground(new java.awt.Color(51, 102, 255));

        endTimeLabel.setForeground(new java.awt.Color(51, 102, 255));
        endTimeLabel.setText("End Time:");

        endTaskTime.setText("12:00pm");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(startTaskTime))
                            .addComponent(startTimeLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endTaskTime)
                            .addComponent(endTimeLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(activityName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(subActivity1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 64, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subActivity2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subActivity3, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator5)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(startTimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startTaskTime)
                        .addGap(18, 18, 18)
                        .addComponent(endTimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endTaskTime))
                    .addComponent(edit)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(subActivity1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subActivity2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subActivity3))
                    .addComponent(activityName)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        title.setText("Daily Schedule");
        title.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(day)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(86, 86, 86)
                .addComponent(create)
                .addGap(28, 28, 28))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day)
                    .addComponent(create)
                    .addComponent(title))
                .addGap(24, 24, 24)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        createPopUp.setSize(400, 675);
        createPopUp.setVisible(true);
    }//GEN-LAST:event_createActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void subActivity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActivity1ActionPerformed
        if (count1 == 0) {
            Font font = new Font("Segoe UI", Font.PLAIN, 12);
            Map attributes = font.getAttributes();
            attributes.put(TextAttribute.STRIKETHROUGH, TextAttribute.STRIKETHROUGH_ON);
            Font newFont = new Font(attributes);
            subActivity1.setFont(newFont);
            count1 ++;
        } else {
            Font font = new Font("Segoe UI", Font.PLAIN, 12);
            Map attributes = font.getAttributes();
            attributes.remove(TextAttribute.STRIKETHROUGH);
            Font newFont = new Font(attributes);
            subActivity1.setFont(font);
        }
    }//GEN-LAST:event_subActivity1ActionPerformed

    private void subActivity2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActivity2ActionPerformed
        Font font = new Font("Segoe UI", Font.PLAIN, 12);
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.STRIKETHROUGH, TextAttribute.STRIKETHROUGH_ON);
        Font newFont = new Font(attributes);
        subActivity2.setFont(newFont);
    }//GEN-LAST:event_subActivity2ActionPerformed

    private void subActivity3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActivity3ActionPerformed
        Font font = new Font("Segoe UI", Font.PLAIN, 12);
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.STRIKETHROUGH, TextAttribute.STRIKETHROUGH_ON);
        Font newFont = new Font(attributes);
        subActivity3.setFont(newFont);
    }//GEN-LAST:event_subActivity3ActionPerformed

    private void yesCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesCreateActionPerformed
        daily = true;
    }//GEN-LAST:event_yesCreateActionPerformed

    private void noCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noCreateActionPerformed
        daily = false;
    }//GEN-LAST:event_noCreateActionPerformed

    private void createTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTaskActionPerformed
        subtaskOne = createSubtask1.getText();
        subtaskTwo = createSubtask2.getText(); 
        subtaskThree = createSubtask3.getText();
        addedTask.clear();
        
        try {
            eventName = createTaskName.getText();
            beginTime = createStartTime.getText();
            finishTime = createEndTime.getText();
            
            if (checkEmpty() == false) {
                if (createSubtask1.getText().isEmpty() || createSubtask2.getText().isEmpty() || 
                        createSubtask3.getText().isEmpty()) {
                    subtaskOne = "N/A";
                    subtaskTwo = "N/A";
                    subtaskThree = "N/A";
                }
                
                id++;
                Task newTask = new Task(eventName, beginTime, finishTime, subtaskOne, subtaskTwo,
                        subtaskThree, daily, id);
                tasks.add(newTask);
                addedTask.add(newTask);
                addTask(eventName, beginTime, finishTime, subtaskOne, subtaskTwo, subtaskThree);
                clear();
                createPopUp.setVisible(false);
            } else {
                createOutput.setText("Please make sure you filled out every field");
            }

        } catch (Exception e) {
            createOutput.setText("Please make sure you filled out every field");
        }
    }//GEN-LAST:event_createTaskActionPerformed

    private void editTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTaskActionPerformed
        subtaskOne = createSubtask1.getText();
        subtaskTwo = createSubtask2.getText();
        subtaskThree = createSubtask3.getText();
        addedTask.clear();
        System.out.println("k");

        try {
            System.out.println("09");
            eventName = createTaskName.getText();
            beginTime = createStartTime.getText();
            finishTime = createEndTime.getText();

            if (checkEmpty() == false) {
                System.out.println("1");
                if (createSubtask1.getText().isEmpty() || createSubtask2.getText().isEmpty() || 
                        createSubtask3.getText().isEmpty()) {
                    System.out.println("2");
                    subtaskOne = "N/A";
                    subtaskTwo = "N/A";
                    subtaskThree = "N/A";
                }
                int j = 0;
                System.out.println("f");
                editTask(j, eventName, beginTime, finishTime, subtaskOne, 
            subtaskTwo, subtaskThree);
                System.out.println("hfd");
                clear();
                System.out.println("hsf");
                editPopUp.setVisible(false);
                System.out.println("qwe");
            } else {
                createOutput.setText("Please make sure you filled out every field");
            }
        } catch (Exception e) {
            System.out.println("a");
            createOutput.setText("Please make sure you filled out every field");
        }
    }//GEN-LAST:event_editTaskActionPerformed

    private void yesEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesEditActionPerformed
        daily = true;
    }//GEN-LAST:event_yesEditActionPerformed

    private void noEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noEditActionPerformed
        daily = false;
    }//GEN-LAST:event_noEditActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        editPopUp.setSize(400, 675);
        editPopUp.setVisible(true);
        n = addedTask.get(0).getName();
        st = addedTask.get(0).getStartTime(); 
        et = addedTask.get(0).getEndTime();
        sb1 = addedTask.get(0).getSubtask1();
        sb2 = addedTask.get(0).getSubtask2();
        sb3 = addedTask.get(0).getSubtask3();
        getTask(n, st, et, sb1, sb2, sb3);
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityName;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton create;
    private com.github.lgooddatepicker.components.TimePicker createEndTime;
    private javax.swing.JLabel createEndTimePrompt;
    private javax.swing.JTextField createOutput;
    private javax.swing.JFrame createPopUp;
    private javax.swing.JLabel createRepeatingTaskPrompt;
    private com.github.lgooddatepicker.components.TimePicker createStartTime;
    private javax.swing.JLabel createStartTimePrompt;
    private javax.swing.JTextField createSubtask1;
    private javax.swing.JLabel createSubtask1Prompt;
    private javax.swing.JTextField createSubtask2;
    private javax.swing.JLabel createSubtask2Prompt;
    private javax.swing.JTextField createSubtask3;
    private javax.swing.JLabel createSubtask3Prompt;
    private javax.swing.JButton createTask;
    private javax.swing.JTextField createTaskName;
    private javax.swing.JLabel createTaskNamePrompt;
    private javax.swing.JLabel createTitle;
    private javax.swing.JLabel day;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField editCreateOutput;
    private javax.swing.JLabel editCreateTitle;
    private com.github.lgooddatepicker.components.TimePicker editEndTime;
    private javax.swing.JLabel editEndTimePrompt;
    private javax.swing.JFrame editPopUp;
    private javax.swing.JLabel editRepeatingTaskPrompt;
    private com.github.lgooddatepicker.components.TimePicker editStartTime;
    private javax.swing.JLabel editStartTimePrompt;
    private javax.swing.JTextField editSubtask1;
    private javax.swing.JLabel editSubtask1Prompt;
    private javax.swing.JTextField editSubtask2;
    private javax.swing.JLabel editSubtask2Prompt;
    private javax.swing.JTextField editSubtask3;
    private javax.swing.JLabel editSubtask3Prompt;
    private javax.swing.JButton editTask;
    private javax.swing.JTextField editTaskName;
    private javax.swing.JLabel editTaskNamePrompt;
    private javax.swing.JLabel endTaskTime;
    private javax.swing.JLabel endTimeLabel;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JToggleButton noCreate;
    private javax.swing.JToggleButton noEdit;
    private java.awt.Panel panel1;
    private javax.swing.JLabel startTaskTime;
    private javax.swing.JLabel startTimeLabel;
    private javax.swing.JRadioButton subActivity1;
    private javax.swing.JRadioButton subActivity2;
    private javax.swing.JRadioButton subActivity3;
    private javax.swing.JLabel title;
    private javax.swing.JToggleButton yesCreate;
    private javax.swing.JToggleButton yesEdit;
    // End of variables declaration//GEN-END:variables
}
